import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="min-h-screen flex flex-col justify-between">
        <main className="flex-grow">{children}</main>
        <nav className="fixed bottom-0 w-full bg-white border-t flex justify-around py-2">
          <Link href="/menu">メニュー</Link>
          <Link href="/mypage">マイページ</Link>
          <Link href="/home">ホーム</Link>
          <Link href="/card">カード</Link>
        </nav>
      </body>
    </html>
  );
}
